swagger: '2.0'
info:
  description: >-
    An API expected to be exposed by an OverHide "broker": specification of the
    "broker API" connector in the [OverHide component
    diagram](https://github.com/JakubNer/overhide/raw/master/docs/.images/provided.png).
  version: 1.0.0
  title: OverHide Broker API
  contact:
    email: info@overhide.io
  license:
    name: MIT License
    url: 'https://pages.github.com/JakubNer/overhide/blob/master/LICENSE'
tags:
  - name: capabilities
    description: Discover capabilities of the OverHide broker system.
paths:
  /capabilities/remuneration-providers:
    get:
      summary: List of remuneration providers supported.
      description: >-
        Mapping of remuneration providers to the broker's public address for given
        provider.
      tags:
        - capabilities
      operationId: getRemunerationProviders
      responses:
        200:
          description: >-
            Array of objects each defining one remuneration provider mapping.
          schema:
            type: array
            items:
              $ref: "#/definitions/RemunerationProvider"
definitions:
  RemunerationProvider:
    type: object
    required:
      - key
      - broker-address
    properties:
      key:
        type: string
      broker-address:
        type: string
externalDocs:
  description: OverHide documentation
  url: 'https://pages.github.com/JakubNer/overhide'
