swagger: '2.0'
info:
  description: >-
    An API expected to be exposed by an OverHide "broker": specification of the
    "broker API" connector in the [OverHide component
    diagram](https://github.com/JakubNer/overhide/raw/master/docs/.images/provided.png).
  version: 1.0.0
  title: OverHide Remuneration API
  contact:
    email: info@overhide.io
  license:
    name: MIT License
    url: 'https://pages.github.com/JakubNer/overhide/blob/master/LICENSE'
tags:
  - name: capabilities
    description: Discover capabilities of the OverHide broker system.
paths:
  /capabilities/hash-algorithms:
    get:
      summary: List of hashing algorithms supported.
      description: ''
      tags:
        - capabilities
      operationId: getHashAlgorithms
      responses:
        200:
          description: List of supported hashing algorithms.
          schema:
            $ref: "#/definitions/HashingAlgorithms"
definitions:
  HashingAlgorithms:
    type: array
    items:
      type: string
      enum:
        - SHA256
externalDocs:
  description: OverHide documentation
  url: 'https://pages.github.com/JakubNer/overhide'
